# - menu_name: "Services"

- name: "Home"
  url: "/index.html"
  title: "Home"

- name: "About"
  url: "/about"
  title: "About"

- name: "Contact"
  url: "/contact"
  title: "Contact"

- name: "Services"
  url: "/services"
  title: "Services"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
